#!/usr/bin/env python3
"""
build.py  –  Bündelt alle Python-Backend-Dateien in eine einzige JS-Datei
             (frontend/web/js/engine-src.js), die von app.js direkt geladen
             wird. So braucht die Web-Seite keine ../../-Pfade mehr und
             GitHub Pages kann keine einzelne .py-Datei auslassen oder
             verweigern.

Ausführen (aus dem Repo-Root):
    python3 build.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).parent

PYTHON_DATEIEN = [
    "backend/__init__.py",
    "backend/regeln.py",
    "backend/wuerfel.py",
    "backend/wuerfelfeld.py",
    "backend/cockpit.py",
    "backend/landung.py",
    "backend/spielplan.py",
    "backend/bridge.py",
]


def build():
    sources = {}

    for rel in PYTHON_DATEIEN:
        pfad = ROOT / rel
        text = pfad.read_text(encoding="utf-8")
        sources[rel] = text
        print(f"  {rel}: {len(text):>6} Zeichen")

    # Jede YAML-Datei unter backend/landungen/ wird automatisch mit
    # eingebündelt - neue Flughäfen (z.B. LHR.yaml) tauchen so ohne
    # Anpassung an dieser Datei sowohl in der Engine als auch in der
    # Frontend-Auswahl (backend/landung.py: flughafen_liste()) auf.
    landungen_dir = ROOT / "backend" / "landungen"
    for yaml_pfad in sorted(landungen_dir.glob("*.yaml")):
        rel = f"backend/landungen/{yaml_pfad.name}"
        text = yaml_pfad.read_text(encoding="utf-8")
        sources[rel] = text
        print(f"  {rel}: {len(text):>6} Zeichen")

    out = ROOT / "frontend" / "web" / "js" / "engine-src.js"
    content = (
        "/* AUTO-GENERATED by build.py - nicht manuell bearbeiten */\n"
        "/* Regenerieren: python3 build.py  (aus dem Repo-Root) */\n\n"
        "const ENGINE_SRC = "
        + json.dumps(sources, ensure_ascii=False, indent=2)
        + ";\n"
    )
    out.write_text(content, encoding="utf-8")
    print(f"\nFertig: {out.relative_to(ROOT)}  ({out.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    build()
