#!/usr/bin/env python3
"""
build.py  –  Bündelt alle Python-Backend-Dateien in eine einzige JS-Datei
             (frontend/web/js/engine-src.js), die von app.js direkt geladen
             wird. So braucht die Web-Seite keine ../../-Pfade mehr und
             GitHub Pages kann keine einzelne .py-Datei auslassen oder
             verweigern.

Ausführen (aus dem Repo-Root):
    python3 build.py
"""
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).parent

PYTHON_DATEIEN = [
    "backend/__init__.py",
    "backend/regeln.py",
    "backend/ui_schema.py",
    "backend/wuerfel.py",
    "backend/wuerfelfeld.py",
    "backend/cockpit.py",
    "backend/landung.py",
    "backend/spielplan.py",
    "backend/bridge.py",
]

UI_SCHEMA = "backend/ui_schema.json"


def build():
    sources = {}

    for rel in PYTHON_DATEIEN:
        pfad = ROOT / rel
        text = pfad.read_text(encoding="utf-8")
        sources[rel] = text
        print(f"  {rel}: {len(text):>6} Zeichen")

    schema_path = ROOT / UI_SCHEMA
    schema = json.loads(schema_path.read_text(encoding="utf-8"))
    sources[UI_SCHEMA] = json.dumps(schema, ensure_ascii=False, indent=2) + "\n"
    print(f"  {UI_SCHEMA}: {len(sources[UI_SCHEMA]):>6} Zeichen")

    # Jede YAML-Datei unter backend/landungen/ wird automatisch mit
    # eingebündelt - neue Flughäfen (z.B. LHR.yaml) tauchen so ohne
    # Anpassung an dieser Datei sowohl in der Engine als auch in der
    # Frontend-Auswahl (backend/landung.py: flughafen_liste()) auf.
    landungen_dir = ROOT / "backend" / "landungen"
    for yaml_pfad in sorted(landungen_dir.glob("*.yaml")):
        rel = f"backend/landungen/{yaml_pfad.name}"
        text = yaml_pfad.read_text(encoding="utf-8")
        sources[rel] = text
        print(f"  {rel}: {len(text):>6} Zeichen")

    out = ROOT / "frontend" / "web" / "js" / "engine-src.js"
    content = (
        "/* AUTO-GENERATED by build.py - nicht manuell bearbeiten */\n"
        "/* Regenerieren: python3 build.py  (aus dem Repo-Root) */\n\n"
        "const ENGINE_SRC = "
        + json.dumps(sources, ensure_ascii=False, indent=2)
        + ";\n"
    )
    out.write_text(content, encoding="utf-8")
    print(f"\nFertig: {out.relative_to(ROOT)}  ({out.stat().st_size // 1024} KB)")

    schema_out = ROOT / "frontend" / "web" / "js" / "game-schema.js"
    schema_out.write_text(
        "/* AUTO-GENERATED by build.py - nicht manuell bearbeiten */\n"
        "window.COCKPIT_SCHEMA = " + json.dumps(schema, ensure_ascii=False, indent=2) + ";\n",
        encoding="utf-8",
    )

    # The service worker is cache-first, so its cache key must also change for
    # HTML, CSS and browser JavaScript edits—not only when the Python engine
    # bundle changes.
    cache_inputs = [
        content,
        schema_out.read_text(encoding="utf-8"),
        *[
            (ROOT / rel).read_text(encoding="utf-8")
            for rel in (
                "frontend/web/index.html",
                "frontend/web/multiplayer.html",
                "frontend/web/css/style.css",
                "frontend/web/js/app.js",
                "frontend/web/js/multiplayer.js",
                "frontend/web/sw.js",
            )
        ],
    ]
    digest = hashlib.sha256("".join(cache_inputs).encode("utf-8")).hexdigest()[:12]
    info_out = ROOT / "frontend" / "web" / "js" / "build-info.js"
    info_out.write_text(
        "/* AUTO-GENERATED by build.py - cache version for the service worker */\n"
        f'const COCKPIT_BUILD_VERSION = "{digest}";\n',
        encoding="utf-8",
    )
    print(f"Fertig: {schema_out.relative_to(ROOT)}")
    print(f"Fertig: {info_out.relative_to(ROOT)}")


if __name__ == "__main__":
    build()
